### ISSUE TITLE
VPC_LED_Control Error. No USB connection

### ISSUE THREAD

**Issue by Maxos43** [oernster/joystickgremlin_vpcleds#1]
Hi there, 
Maybe I do something wrong as Im not into programming stuff but I face an unsolvable mystery.
I follow all the step mentionned but when I press the button suppose to change led color I have a window that popup from VPC_LED_Control saying that the Status is : ERROR. No USB connection

My devices are plugged into an usb hub that is plugged into the PC. Everything is perfectly working with joystick gremlin and they are well recognize. 
Idk why I have this error. If someone can help me it would be much appreciated!

**Comment by oernster** [comment]
Hi,

Are you able to configure LEDs using the VPC software WITHOUT using JG and the plugin?

Oliver

From: Maxos43 ***@***.***>
Date: Thursday, 16 December 2021 at 15:18
To: oernster/joystickgremlin_vpcleds ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [oernster/joystickgremlin_vpcleds] VPC_LED_Control Error. No USB connection (Issue #1)

Hi there,
Maybe I do something wrong as Im not into programming stuff but I face an unsolvable mystery.
I follow all the step mentionned but when I press the button suppose to change led color I have a window that popup from VPC_LED_Control saying that the Status is : ERROR. No USB connection

My devices are plugged into an usb hub that is plugged into the PC. Everything is perfectly working with joystick gremlin and they are well recognize.
Idk why I have this error. If someone can help me it would be much appreciated!

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foernster%2Fjoystickgremlin_vpcleds%2Fissues%2F1&data=04%7C01%7C%7C5d7fee010e374724da2808d9c0a74e44%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752647067935741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kP73k6FXaOUMpYLhuEFXB6WTUIP74djogy%2Bjxf8wdBo%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALJVX54NW2VB3A7QK7GPTLURH7MDANCNFSM5KGSM2BQ&data=04%7C01%7C%7C5d7fee010e374724da2808d9c0a74e44%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752647067935741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aINz1uaIF0huHiOSeDRGHZJoUmgm3Hyr5WFqJDrCCYM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C5d7fee010e374724da2808d9c0a74e44%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752647067945733%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=azP4mhZe5ZYx1iJ5kFzHBD5eLI%2FMQ%2ByftxJzQVOKQeA%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C5d7fee010e374724da2808d9c0a74e44%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752647067945733%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3c8lsfUlBF6IPx1BRASj8ORR9X1T3cgF9ro5SdLdx3M%3D&reserved=0>.

**Comment by Maxos43** [comment]
Yes, it works properly from the VPC configuration Tool

**Comment by oernster** [comment]
When I had my setup, I used a CM3 throttle (connected by USB to my PC) with an aux connection to my CPv2 and my Constellation Alpha R grip/WarBRD base was separately connected by USB.
Can you try this, please?  It shouldn’t matter though.  Another possibility is that you have 2 instances of JG running.

From: Maxos43 ***@***.***>
Date: Thursday, 16 December 2021 at 15:40
To: oernster/joystickgremlin_vpcleds ***@***.***>
Cc: oernster ***@***.***>, Comment ***@***.***>
Subject: Re: [oernster/joystickgremlin_vpcleds] VPC_LED_Control Error. No USB connection (Issue #1)

Yes, it works properly from the VPC configuration Tool

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foernster%2Fjoystickgremlin_vpcleds%2Fissues%2F1%23issuecomment-995933983&data=04%7C01%7C%7C29b2d8033eed41b5721208d9c0aa6069%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752660253523498%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fygvBPWHuf0Shev238SqVv6Px81vLY6NO4y6jwLxPNw%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALJVXYGNJAC2G5USW5V5HDURIB6PANCNFSM5KGSM2BQ&data=04%7C01%7C%7C29b2d8033eed41b5721208d9c0aa6069%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752660253523498%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3mauAJAd4Z0S%2FeWVAe49SjAiCzhAxnomLMEMLFpRIdk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C29b2d8033eed41b5721208d9c0aa6069%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752660253533499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lk8r3LskNgI5UnNCm%2FRntOXCnVk6lDXtiRhGCtowNB8%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C29b2d8033eed41b5721208d9c0aa6069%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752660253543495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PxJxYqLXoKkzCfinyGp9QUkwm%2Ff0Z2FFHwLdROZa4R4%3D&reserved=0>.

**Comment by Maxos43** [comment]
I'll test that this weekend as I have to screw up my cable management on my chair to do that. 
anyway I plan to modify a bit my setup this weekend. 
I'll keep in touch. 
Thanks for the work and the quick answer !

**Comment by oernster** [comment]
No worries.  I actually suspect a JG issue.  Perhaps jump on the JG discord channel in the HOTAS/HOSAS/SimPit discord channel?  You can ask the author of JG there.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Maxos43** [comment]
Hi oernster! 
I did some test and when the Stick is directly plug into the computer it works. The problem is that my sticks are chair mount and I have to use an USB hub (otherwise it's to messy). Curently I use this one from Monstertech (1x Hub USB 3.0 Anker Ultra-Slim // monster.tech/fr/produit/kit-de-cable-management/).
Any way to makes this functional? 
Thanks a lot for your time :)

**Comment by oernster** [comment]
Try a powered USB hub

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Maxos43** [comment]
Probably that but no I can't put a powered USB under my chair. The aim is to plug minimal thing into the computer when I switch chair. 
Anyway I'll learn to use Virpil Software Led into the Virpil Software this will be painfull :'D
Thanks for the help!

**Comment by oernster** [comment]
Another option is to buy a USB female to USB male extension lead amazon basics item

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by oernster** [comment]
You won't get all the flexibility you get with my software with the virpil default tool.  With my plug in with joystick gremlin you'll get a whole load of extra configurable features with leds

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by oernster** [comment]
If you're happy with the possible solutions I have offered I will close this ticket now.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Maxos43** [comment]
You're right that's working plug into an powered USB HUB. 
Thanks for the help, you can close the ticket! 
Have a nice day

**Comment by oernster** [comment]
Awesome!  Thanks for letting me know.  Will close.

From: Maxos43 ***@***.***>
Date: Monday, 20 December 2021 at 09:10
To: oernster/joystickgremlin_vpcleds ***@***.***>
Cc: oernster ***@***.***>, Comment ***@***.***>
Subject: Re: [oernster/joystickgremlin_vpcleds] VPC_LED_Control Error. No USB connection (Issue #1)

You're right that's working plug into an powered USB HUB.
Thanks for the help, you can close the ticket!
Have a nice day

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foernster%2Fjoystickgremlin_vpcleds%2Fissues%2F1%23issuecomment-997733740&data=04%7C01%7C%7Cf18c565ce52f403373ae08d9c3989178%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755882313466815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9LSR9szTTHvKiDFJEB8mBU9VurPq6S3yc7eL1OrNt8s%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALJVX4UUDXMVMDGSB6EUTDUR3XIJANCNFSM5KGSM2BQ&data=04%7C01%7C%7Cf18c565ce52f403373ae08d9c3989178%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755882313466815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Oq%2B8lvJgWROrE84sOq06ij8TDKXUHsC1ufUEaHzSsJ0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf18c565ce52f403373ae08d9c3989178%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755882313476812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AISiDoBJQJfnIPWk0ZkVBNJl8oRr7jGz9VU6u6%2FmH6M%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cf18c565ce52f403373ae08d9c3989178%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755882313476812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WPK%2Fyn1Mz%2B3WgU%2Bls8IpNrFvvFMuDQXeBywcUUSBAo8%3D&reserved=0>.
